fixtures:
    forge_modules:
        apt: 'puppetlabs/apt'
        powershell: 'joshcooper/powershell'
        registry: 'puppetlabs/registry'
        stdlib: 'puppetlabs/stdlib'
    symlinks:
      stackdriver: "#{source_dir}"
