fixtures:
    forge_modules:
        apt: 'puppetlabs/apt'
        registry: 'puppetlabs/registry'
        stdlib: 'puppetlabs/stdlib'
        stdlib: 'joshcooper/powershell'
    symlinks:
      stackdriver: "#{source_dir}"
