fixtures:
    forge_modules:
        apt: 'puppetlabs/apt'
        powershell: 'joshcooper/powershell'
        registry: 'puppetlabs/registry'
        stdlib:
            repo: 'puppetlabs/stdlib'
            ref: '4.12.0'
    symlinks:
      stackdriver: "#{source_dir}"
